anomaly_graphs_per_epoch: 4
embedding_dim: 64
hidden_dim: 128
learning_rate: 0.0005
loss_weights:
  consistency: 1.0
  regularization: 0.01
  separation: 2.0
node_feature_dim: 16
normal_graphs_per_epoch: 8
num_epochs: 25
num_nodes: 100
